# Generated by Django 3.1 on 2020-10-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.itemrole'),
            preserve_default=False,
        ),
    ]
