# Generated by Django 3.1 on 2020-10-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201009_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_role',
        ),
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_role_count', models.IntegerField()),
                ('sold_role_count', models.IntegerField()),
                ('total_role_count', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.item')),
            ],
        ),
    ]
