# Generated by Django 3.1 on 2020-10-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201009_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('in_stock', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarpetDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_Carpet_width', models.FloatField()),
                ('available_Carpet_length', models.FloatField()),
                ('colour', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('Carpet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpet')),
            ],
        ),
        migrations.CreateModel(
            name='CarpetInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_role_count', models.IntegerField()),
                ('sold_role_count', models.IntegerField()),
                ('total_role_count', models.IntegerField()),
                ('Carpet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpet')),
            ],
        ),
        migrations.CreateModel(
            name='CarpetRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_width', models.FloatField()),
                ('role_length', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('Carpet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpet')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCarpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carpet_width', models.FloatField()),
                ('Carpet_length', models.FloatField()),
                ('mrp', models.FloatField()),
                ('discount', models.FloatField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.order')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpetrole')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderCarpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carpet_width', models.FloatField()),
                ('Carpet_length', models.FloatField()),
                ('Carpet_cost', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('Carpet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpet')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.purchaseorder')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='iteminventory',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemrole',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='CarpetCategory',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemDescription',
        ),
        migrations.DeleteModel(
            name='ItemInventory',
        ),
        migrations.DeleteModel(
            name='ItemRole',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.AddField(
            model_name='carpet',
            name='Carpet_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpetcategory'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
