# Generated by Django 3.1 on 2020-10-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201009_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_r1_width', models.FloatField()),
                ('roll_r1_length', models.FloatField()),
                ('roll_r2_width', models.FloatField()),
                ('roll_r2_length', models.FloatField()),
                ('added_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet_width', models.FloatField()),
                ('carpet_length', models.FloatField()),
                ('mrp', models.FloatField()),
                ('discount', models.FloatField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CarpetCategory',
            new_name='CarpetType',
        ),
        migrations.RemoveField(
            model_name='carpetrole',
            name='Carpet_id',
        ),
        migrations.RemoveField(
            model_name='ordercarpet',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ordercarpet',
            name='role_id',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='Carpet_category',
            new_name='carpet_type',
        ),
        migrations.RenameField(
            model_name='carpetinventory',
            old_name='available_role_count',
            new_name='available_roll_count',
        ),
        migrations.RenameField(
            model_name='carpetinventory',
            old_name='Carpet_id',
            new_name='carpet',
        ),
        migrations.RenameField(
            model_name='carpetinventory',
            old_name='sold_role_count',
            new_name='sold_roll_count',
        ),
        migrations.RenameField(
            model_name='carpetinventory',
            old_name='total_role_count',
            new_name='total_roll_count',
        ),
        migrations.RenameField(
            model_name='carpettype',
            old_name='category_name',
            new_name='carpet_type',
        ),
        migrations.RenameField(
            model_name='purchaseordercarpet',
            old_name='Carpet_id',
            new_name='carpet',
        ),
        migrations.RenameField(
            model_name='purchaseordercarpet',
            old_name='Carpet_cost',
            new_name='carpet_cost',
        ),
        migrations.RenameField(
            model_name='purchaseordercarpet',
            old_name='Carpet_length',
            new_name='carpet_length',
        ),
        migrations.RenameField(
            model_name='purchaseordercarpet',
            old_name='Carpet_width',
            new_name='carpet_width',
        ),
        migrations.AddField(
            model_name='carpet',
            name='available_carpet_length',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpet',
            name='available_carpet_width',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpet',
            name='colour',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarpetDescription',
        ),
        migrations.DeleteModel(
            name='CarpetRole',
        ),
        migrations.DeleteModel(
            name='OrderCarpet',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='carpet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpet'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.order'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='roll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpetroll'),
        ),
        migrations.AddField(
            model_name='carpetroll',
            name='carpet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carpet'),
        ),
    ]
