# Generated by Django 3.1 on 2020-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201009_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpet',
            old_name='available_carpet_length',
            new_name='available_carpet',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='available_carpet_width',
        ),
        migrations.AddField(
            model_name='carpetroll',
            name='available_area',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
